// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5cXVAeYmq0ORT6j5Qwvpn4HT6GPOlhE',
    appId: '1:652651089184:web:596ba1a3af4c02c16e5b45',
    messagingSenderId: '652651089184',
    projectId: 'assigntodo1',
    authDomain: 'assigntodo1.firebaseapp.com',
    storageBucket: 'assigntodo1.firebasestorage.app',
    measurementId: 'G-8DYWCD2RCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNsjTrqkXZiniH_iheBgOIe1O7EgsAyw',
    appId: '1:652651089184:android:5ae2321fa30c0d4a6e5b45',
    messagingSenderId: '652651089184',
    projectId: 'assigntodo1',
    storageBucket: 'assigntodo1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehXwoYejJnV0ykFVO9YUgwxGQbQDzSQE',
    appId: '1:652651089184:ios:a85a94ac638a432c6e5b45',
    messagingSenderId: '652651089184',
    projectId: 'assigntodo1',
    storageBucket: 'assigntodo1.firebasestorage.app',
    iosBundleId: 'com.example.contactSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDehXwoYejJnV0ykFVO9YUgwxGQbQDzSQE',
    appId: '1:652651089184:ios:da7436d99e951a986e5b45',
    messagingSenderId: '652651089184',
    projectId: 'assigntodo1',
    storageBucket: 'assigntodo1.firebasestorage.app',
    iosBundleId: 'com.example.contactSync.RunnerTests',
  );
}
